# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
   
jobs:
  robot_test:
    runs-on: ubuntu-latest
    - name: Robot Framework
      uses: tarathep/robotframework-github-action@v1.0
      with:
        tests_dir: '${{ github.workspace }}/testes/'
        reports_dir: '${{ github.workspace }}/testes/reports'
