name: run unit tests of feature branches

on:
  push:
    branches: 
      "feature/*"  

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: run unit test
        run: robot .
      
